vim.o.termguicolors = true
vim.g.colors_name = 'blackberry'

-- ============================================================================
-- Palette (Blackberry — adapted from Zed theme by etieppo)
-- ============================================================================
local p = {
  -- Backgrounds
  transparent  = '#000000',
  bg0          = '#060609',   -- mais fundo ainda (janelas inativas)
  bg1          = '#0a0a0d',   -- fundo principal (editor)
  bg2          = '#08080b',   -- painéis, sidebar, statusbar
  bg3          = '#0f0f14',   -- linhas ativas, float
  bg4          = '#14141c',   -- seleção leve, indent ativo
  bg5          = '#1a1a26',   -- seleção visual, hover
  bgBlue       = '#11161f',   -- winter blue (virtual text info bg)
  bgGreen      = '#0d1410',   -- winter green (virtual text hint bg)
  bgRed        = '#160d0d',   -- winter red (virtual text error bg)
  bgYellow     = '#15130a',   -- winter yellow (virtual text warn bg)

  -- Foreground / Text
  fg           = '#a9b1d6',   -- texto principal
  fgMuted      = '#787c99',   -- texto secundário / mutado
  fgDim        = '#545470',   -- texto desabilitado / muito suave
  fgBright     = '#c5cae9',   -- texto destacado / bright white terminal

  -- Borders / Structural
  border       = '#191921',   -- borda padrão
  borderFaint  = '#14141a',   -- borda ainda mais suave
  borderFocus  = '#545c7e',   -- borda com foco

  -- Accent / Selection
  selection    = '#3d59a144', -- seleção visual (alpha)
  selectionBg  = '#1e202e',   -- linha ativa / seleção sólida
  matchBg      = '#3d59a166',  -- search match bg

  -- Syntax — Core
  keyword      = '#702ded',   -- keywords: if, for, return, class...
  keywordAlt   = '#bb9af7',   -- keyword.function, keyword.type (lavanda)
  func         = '#7aa2f7',   -- funções e métodos (azul médio)
  funcBuiltin  = '#0db9d7',   -- funções built-in (ciano)
  type_        = '#0db9d7',   -- tipos e interfaces (ciano)
  typeParam    = '#3a5d81',   -- parâmetros de tipo / generics (azul escuro)
  property     = '#7dcfff',   -- property no Zed (#7dcfff) — ciano claro, distinto de type
  namespace_   = '#0db9d7',   -- módulos e namespaces (ciano, como type)
  variable     = '#c0caf5',   -- variable no Zed (#c0caf5) — branco lavanda
  param        = '#e0687a',   -- variable.parameter no Zed (#e0687a)
  constant     = '#b8003a',   -- constantes nomeadas (vermelho escuro — Zed constant: #b8003a)
  constantAlt  = '#c0768e',   -- constant.builtin: nil, true, false (rosa acinzentado — Zed: #c0768e)
  operator     = '#89ddff',   -- operadores (ciano claro)
  string_      = '#03826b',   -- strings (verde escuro)
  stringAlt    = '#85d0b7',   -- string.doc / heredoc (verde claro)
  regex        = '#b4f9f8',   -- regex / string.special (ciano brilhante)
  number       = '#c0768e',   -- números (rosa acinzentado — Zed number: #c0768e, igual constant.builtin)
  comment      = '#444b6a',   -- comentários (cinza azulado escuro)
  tag          = '#892a3b',   -- tags HTML/JSX (vermelho escuro)
  tagAttr      = '#556779',   -- atributos de tag (cinza azulado — como string muted)
  macro        = '#737aa2',   -- macros e preproc (cinza azulado médio)

  -- Errors / Diagnostics
  error_       = '#f7768e',   -- erro (terminal ansi red)
  warning      = '#e0af68',   -- aviso (terminal ansi yellow)
  info         = '#7aa2f7',   -- informação (terminal ansi blue)
  hint         = '#41a6b5',   -- dica (terminal ansi green)

  -- Git
  added        = '#a9b1d6',   -- adicionado (fg — como no Zed version_control.added era ciano claro)
  modified     = '#e0af68',   -- modificado (amarelo)
  deleted      = '#f7768e',   -- deletado (vermelho suave)

  -- Special
  purple       = '#bb9af7',   -- lavanda / violet
  salmon       = '#e0687a',   -- rosa salmon (parâmetros)
  teal         = '#41a6b5',   -- teal (terminal green)
  cyan         = '#7dcfff',   -- ciano claro (propriedades)
  cyanBright   = '#b4f9f8',   -- ciano brilhante (regex)
  crimson      = '#b8003a',   -- vermelho escuro (constantes)
  crimsonBright= '#f7768e',   -- vermelho claro (errors)
  darkRed      = '#892a3b',   -- vermelho muito escuro (tags)
}




local set = vim.api.nvim_set_hl

-- ============================================================================
-- UI / Editor
-- ============================================================================
set(0, 'WinSeparator',       { fg = p.transparent})
set(0, 'Normal',             { fg = p.fg,         bg = p.bg0 })
set(0, 'NormalNC',           { fg = p.fg,         bg = p.bg0 })
set(0, 'NormalFloat',        { fg = p.fg,         bg = p.bg3 })
set(0, 'CursorLine',         { bg = p.bg3 })
set(0, 'CursorLineNr',       { fg = p.keyword,    bold = false })
set(0, 'LineNr',             { fg = p.fgDim })
set(0, 'NonText',            { fg = p.bg5 })
set(0, 'EndOfBuffer',        { fg = p.bg3 })
set(0, 'SignColumn',         { fg = p.fg })
set(0, 'Folded',             { fg = p.fgMuted,    bg = p.bg4 })
set(0, 'FoldColumn',         { fg = p.fgMuted })
set(0, 'ColorColumn',        { bg = p.bg4 })
set(0, 'Conceal',            { fg = p.bg5 })
set(0, 'MatchParen',         { fg = p.teal,       bold = true })
set(0, 'Search',             { fg = p.bg1,        bg = p.keyword })
set(0, 'IncSearch',          { fg = p.bg1,        bg = p.teal })
set(0, 'Visual',             { bg = p.bg5 })
set(0, 'Pmenu',              { fg = p.fg,         bg = p.bg3 })
set(0, 'PmenuSel',           { bg = p.bg4 })
set(0, 'PmenuThumb',         { bg = p.fgMuted })
set(0, 'TabLine',            { fg = p.fg,         bg = p.bg4 })
set(0, 'TabLineSel',         { fg = p.bg2,        bg = p.fgMuted })
set(0, 'TabLineFill',        { bg = p.bg2 })
set(0, 'VertSplit',          { fg = p.bg5 })
set(0, 'StatusLine',         { fg = p.fg,         bg = p.bg4 })
set(0, 'StatusLineNC',       { fg = p.fgDim,      bg = p.bg3 })
set(0, 'WinBar',             { fg = p.fgMuted,    bg = p.bg3,  bold = true })
set(0, 'WinBarNC',           { fg = p.fgMuted,    bg = p.bg3,  bold = true })
set(0, 'FloatBorder',        { fg = p.bg5 })
set(0, 'FloatShadow',        { blend = 80 })
set(0, 'FloatShadowThrough', { blend = 100 })
set(0, 'Cursor',             { fg = p.bg3,        bg = p.teal })
set(0, 'TermCursor',         { reverse = true })
set(0, 'Whitespace',         { fg = p.bg5 })

-- ============================================================================
-- Syntax (fallback sem Treesitter)
-- ============================================================================
set(0, 'Comment',      { fg = p.comment,   italic = true })
set(0, 'Keyword',      { fg = p.keyword })
set(0, 'Identifier',   { fg = p.fg })
set(0, 'Function',     { fg = p.func })
set(0, 'String',       { fg = p.string_ })
set(0, 'Number',       { fg = p.number })
set(0, 'Boolean',      { fg = p.constantAlt })
set(0, 'Float',        { fg = p.number })
set(0, 'Type',         { fg = p.type_ })
set(0, 'Operator',     { fg = p.operator })
set(0, 'Constant',     { fg = p.constant })
set(0, 'PreProc',      { fg = p.macro })
set(0, 'Special',      { fg = p.macro })
set(0, 'Statement',    { fg = p.keyword })
set(0, 'Conditional',  { fg = p.keyword })
set(0, 'Repeat',       { fg = p.keyword })
set(0, 'Label',        { fg = p.type_ })
set(0, 'Exception',    { fg = p.crimsonBright })
set(0, 'Include',      { fg = p.fgMuted })
set(0, 'Define',       { fg = p.fgMuted })
set(0, 'Macro',        { fg = p.macro })
set(0, 'StorageClass', { fg = p.keyword })
set(0, 'Structure',    { fg = p.type_ })
set(0, 'Typedef',      { fg = p.type_ })
set(0, 'Title',        { fg = p.type_,     bold = true })
set(0, 'Underlined',   { underline = true })
set(0, 'Bold',         { bold = true })
set(0, 'Italic',       { italic = true })
set(0, 'Directory',    { fg = p.macro })

-- ============================================================================
-- Diagnostic
-- ============================================================================
set(0, 'DiagnosticError',   { fg = p.error_ })
set(0, 'DiagnosticWarn',    { fg = p.warning })
set(0, 'DiagnosticInfo',    { fg = p.info })
set(0, 'DiagnosticHint',    { fg = p.hint })
set(0, 'DiagnosticOk',      { fg = p.hint })
set(0, 'DiagnosticUnderlineError', { undercurl = true, sp = p.error_ })
set(0, 'DiagnosticUnderlineWarn',  { undercurl = true, sp = p.warning })
set(0, 'DiagnosticUnderlineInfo',  { undercurl = true, sp = p.info })
set(0, 'DiagnosticUnderlineHint',  { undercurl = true, sp = p.hint })
set(0, 'DiagnosticUnderlineOk',    { undercurl = true, sp = p.hint })
set(0, 'DiagnosticVirtualTextError', { fg = p.error_,  bg = p.bgRed })
set(0, 'DiagnosticVirtualTextWarn',  { fg = p.warning, bg = p.bgYellow })
set(0, 'DiagnosticVirtualTextInfo',  { fg = p.info,    bg = p.bgBlue })
set(0, 'DiagnosticVirtualTextHint',  { fg = p.hint,    bg = p.bgGreen })
set(0, 'DiagnosticVirtualTextOk',    { fg = p.hint,    bg = p.bgGreen })
set(0, 'DiagnosticDeprecated',       { strikethrough = true })

-- ============================================================================
-- Git / Diff
-- ============================================================================
set(0, 'DiffAdd',    { bg = p.bgGreen })
set(0, 'DiffDelete', { bg = p.bgRed })
set(0, 'DiffChange', { bg = p.bgYellow })
set(0, 'DiffText',   { bg = p.bg5 })
set(0, 'GitSignsAdd',            { fg = p.added })
set(0, 'GitSignsChange',         { fg = p.modified })
set(0, 'GitSignsDelete',         { fg = p.deleted })
set(0, 'GitSignsAddNr',          { fg = p.added })
set(0, 'GitSignsChangeNr',       { fg = p.modified })
set(0, 'GitSignsDeleteNr',       { fg = p.deleted })
set(0, 'GitSignsStagedAdd',      { fg = p.added })
set(0, 'GitSignsStagedChange',   { fg = p.modified })
set(0, 'GitSignsStagedDelete',   { fg = p.deleted })

-- ============================================================================
-- LSP
-- ============================================================================
set(0, 'LspReferenceText',             { bg = p.bg4 })
set(0, 'LspReferenceRead',             { bg = p.bg4 })
set(0, 'LspReferenceWrite',            { bg = p.bg4 })
set(0, 'LspCodeLens',                  { fg = p.fgMuted })
set(0, 'LspCodeLensSeparator',         { fg = p.fgMuted })
set(0, 'LspInlayHint',                 { fg = p.fgMuted,   bg = p.bg4 })
set(0, 'LspSignatureActiveParameter',  { fg = p.teal,      bold = true })
set(0, 'LspFloatWinNormal',            { bg = p.bg2 })
set(0, 'LspFloatWinBorder',            { fg = p.bg5 })
set(0, 'LspSagaHoverBorder',           { fg = p.fgMuted })
set(0, 'LspSagaSignatureHelpBorder',   { fg = p.crimsonBright })
set(0, 'LspSagaCodeActionBorder',      { fg = p.fgMuted })
set(0, 'LspSagaRenameBorder',          { fg = p.fgMuted })
set(0, 'LspSagaDefPreviewBorder',      { fg = p.fgMuted })
set(0, 'LspSagaFinderSelection',       { fg = p.bg4 })
set(0, 'LspTroubleNormal',             { fg = p.fgMuted,   bg = p.bg2 })
set(0, 'LspTroubleText',               { fg = p.fg })
set(0, 'LspTroubleCount',              { fg = p.purple,    bg = p.fgMuted })

-- ============================================================================
-- Treesitter & Semantic Tokens
-- ============================================================================

-- ── Variables ────────────────────────────────────────────────────────────────
-- Zed JSON:  variable=#c0caf5  |  variable.parameter=#e0687a  |  property=#7dcfff
set(0, '@variable',           { fg = p.variable })
set(0, '@variable.builtin',   { fg = p.variable })                 -- self (no Zed = variable color)
set(0, '@variable.member',    { fg = p.property })                 -- field access: foo.bar
set(0, '@variable.parameter', { fg = p.param })                    -- na definição fn f(x: ...)

-- ── Constants ────────────────────────────────────────────────────────────────
set(0, '@constant',          { fg = p.constant })
set(0, '@constant.builtin',  { fg = p.constantAlt,  bold = true })
set(0, '@constant.macro',    { fg = p.macro })

-- ── Namespaces / modules ─────────────────────────────────────────────────────
set(0, '@module',         { fg = p.namespace_ })
set(0, '@module.builtin', { fg = p.namespace_,  bold = true })
set(0, '@namespace',      { fg = p.namespace_ })

-- ── Functions ────────────────────────────────────────────────────────────────
set(0, '@function',              { fg = p.func })
set(0, '@function.builtin',      { fg = p.funcBuiltin })
set(0, '@function.call',         { fg = p.func })
set(0, '@function.macro',        { fg = p.macro })
set(0, '@function.method',       { fg = p.func })
set(0, '@function.method.call',  { fg = p.func })
set(0, '@constructor',           { fg = p.type_ })

-- ── Parameters ───────────────────────────────────────────────────────────────
set(0, '@parameter', { fg = p.param })

-- ── Keywords ─────────────────────────────────────────────────────────────────
set(0, '@keyword',                     { fg = p.keyword })
set(0, '@keyword.function',            { fg = p.keywordAlt })
set(0, '@keyword.operator',            { fg = p.operator })
set(0, '@keyword.return',              { fg = p.keyword,    italic = true })
set(0, '@keyword.import',              { fg = p.property })        -- Zed: #7dcfff
set(0, '@keyword.modifier',            { fg = p.keyword })
set(0, '@keyword.repeat',              { fg = p.keyword })
set(0, '@keyword.conditional',         { fg = p.keyword })
set(0, '@keyword.conditional.ternary', { fg = p.keyword })
set(0, '@keyword.exception',           { fg = p.crimsonBright })
set(0, '@keyword.type',                { fg = p.keywordAlt })

-- ── Types ────────────────────────────────────────────────────────────────────
set(0, '@type',            { fg = p.type_ })
set(0, '@type.builtin',    { fg = p.funcBuiltin })
set(0, '@type.definition', { fg = p.type_,     bold = true })
set(0, '@type.qualifier',  { fg = p.keyword })

-- ── Properties / fields ──────────────────────────────────────────────────────
-- Zed JSON: property=#7dcfff (ciano claro) — distinto de variable
set(0, '@property', { fg = p.property })
set(0, '@field',    { fg = p.property })

-- ── Strings ──────────────────────────────────────────────────────────────────
set(0, '@string',              { fg = p.string_ })
set(0, '@string.regex',        { fg = p.regex })
set(0, '@string.regexp',       { fg = p.regex })
set(0, '@string.escape',       { fg = p.macro,    bold = true })
set(0, '@string.special',      { fg = p.regex })
set(0, '@string.special.url',  { fg = p.cyan,     italic = true, underline = true })
set(0, '@string.special.path', { fg = p.cyan,     italic = true })
set(0, '@string.documentation',{ fg = p.stringAlt, italic = true })

-- ── Characters ───────────────────────────────────────────────────────────────
set(0, '@character',         { fg = p.stringAlt })  -- Zed character=#85d0b7
set(0, '@character.special', { fg = p.regex })      -- Zed character.special=#b4f9f8

-- ── Numbers ──────────────────────────────────────────────────────────────────
-- Zed JSON: number=#c0768e (igual constant.builtin) — p.number já corrigido no palette
set(0, '@number',       { fg = p.number })
set(0, '@number.float', { fg = p.number })

-- ── Operators ────────────────────────────────────────────────────────────────
set(0, '@operator', { fg = p.operator })

-- ── Pontuação ────────────────────────────────────────────────────────────────
set(0, '@punctuation.delimiter', { fg = p.fg })
set(0, '@punctuation.bracket',   { fg = p.fgMuted })
set(0, '@punctuation.special',   { fg = p.constant })   -- Zed: #b8003a

-- ── Atributos ────────────────────────────────────────────────────────────────
-- Rust: #[derive(Debug)] — o #[ e ] ficam em p.constant, mas o CONTEÚDO varia:
-- derive(...)  -> @lsp.type.derive  -> p.funcBuiltin (é uma macro-like, não constante)
-- #[allow(...)] etc -> @attribute.builtin -> p.macro
set(0, '@attribute',                     { fg = p.macro })
set(0, '@attribute.builtin',             { fg = p.macro })
set(0, '@punctuation.special.attribute', { fg = p.constant })   -- o # e os [ ]
set(0, '@lsp.type.attribute',            { fg = p.macro })
set(0, '@lsp.type.derive',               { fg = p.funcBuiltin }) -- derive(...)
set(0, '@lsp.type.attributeBracket',     { fg = p.constant })

-- ── Comments ─────────────────────────────────────────────────────────────────
set(0, '@comment',               { fg = p.comment,   italic = true })
set(0, '@comment.note',          { fg = p.bg2,        bg = p.info })
set(0, '@comment.todo',          { fg = p.bg2,        bg = p.teal })
set(0, '@comment.warning',       { fg = p.bg2,        bg = p.warning })
set(0, '@comment.error',         { fg = p.bg2,        bg = p.error_ })
set(0, '@comment.documentation', { fg = p.stringAlt,  italic = true })

-- ── Markup ────────────────────────────────────────────────────────────────────
set(0, '@markup',               { fg = p.fg })
set(0, '@markup.heading',       { fg = p.type_,    bold = true })
set(0, '@markup.heading.1',     { fg = p.type_,    bold = true })
set(0, '@markup.heading.2',     { fg = p.type_,    bold = true })
set(0, '@markup.heading.3',     { fg = p.func,     bold = true })
set(0, '@markup.heading.4',     { fg = p.func,     bold = true })
set(0, '@markup.heading.5',     { fg = p.property })
set(0, '@markup.heading.6',     { fg = p.fgMuted })
set(0, '@markup.strong',        { fg = p.fgBright, bold = true })
set(0, '@markup.italic',        { italic = true })
set(0, '@markup.strikethrough', { fg = p.fg,       strikethrough = true })
set(0, '@markup.link',          { fg = p.func,     bold = true })
set(0, '@markup.link.url',      { fg = p.cyan,     underline = true })
set(0, '@markup.link.label',    { fg = p.property })
set(0, '@markup.list',          { fg = p.property })
set(0, '@markup.list.checked',  { fg = p.fg })
set(0, '@markup.list.unchecked',{ fg = p.teal })
set(0, '@markup.raw',           { fg = p.macro,    italic = true })
set(0, '@markup.raw.block',     { fg = p.fgMuted })
set(0, '@markup.quote',         { fg = p.fgMuted,  italic = true })
set(0, '@markup.math',          { fg = p.property })

-- ── Tags (HTML/JSX/TSX/XML) ───────────────────────────────────────────────────
set(0, '@tag',           { fg = p.tag })
set(0, '@tag.builtin',   { fg = p.tag })
set(0, '@tag.attribute', { fg = p.tagAttr,  italic = true })
set(0, '@tag.delimiter', { fg = p.fgDim })

-- ── Overrides por linguagem ───────────────────────────────────────────────────
set(0, '@constructor.lua',   { fg = p.fg })
set(0, '@label.json',        { fg = p.property })
set(0, '@property.json',     { fg = p.property })
set(0, '@tag.attribute.tsx', { fg = p.tagAttr, italic = true })
set(0, '@tag.attribute.jsx', { fg = p.tagAttr, italic = true })

-- ── LSP semantic tokens (genéricos) ──────────────────────────────────────────
set(0, '@lsp.type.interface',     { fg = p.macro })
set(0, '@lsp.type.enum',          { fg = p.type_ })
set(0, '@lsp.type.enumMember',    { fg = p.constant })
set(0, '@lsp.type.struct',        { fg = p.type_ })
set(0, '@lsp.type.class',         { fg = p.type_ })
set(0, '@lsp.type.typeParameter', { fg = p.typeParam })
set(0, '@lsp.type.namespace',     { fg = p.namespace_ })
set(0, '@lsp.type.macro',         { fg = p.macro })
set(0, '@lsp.type.variable',      { link = '@variable' })
set(0, '@lsp.type.parameter',     { fg = p.variable })  -- uso de param = neutro (só def é salmon)
set(0, '@lsp.type.property',      { fg = p.property })  -- Zed JSON: property=#7dcfff
set(0, '@lsp.type.function',      { link = '@function' })
set(0, '@lsp.type.method',        { link = '@function.method' })
set(0, '@lsp.type.keyword',       { link = '@keyword' })
set(0, '@lsp.type.string',        { link = '@string' })
set(0, '@lsp.type.number',        { link = '@number' })
set(0, '@lsp.type.operator',      { link = '@operator' })
set(0, '@lsp.type.comment',       { link = '@comment' })
set(0, '@lsp.type.decorator',     { fg = p.macro })
set(0, '@lsp.type.event',         { fg = p.constant })
set(0, '@lsp.type.modifier',      { fg = p.keyword })
set(0, '@lsp.type.regexp',        { fg = p.regex })
set(0, '@lsp.mod.deprecated',     { strikethrough = true })
set(0, '@lsp.mod.readonly',       { fg = p.constant })
set(0, '@lsp.mod.static',         { fg = p.type_,    bold = true })

-- ── rust-analyzer specific (semantic tokens) ─────────────────────────────────
-- Tokens emitidos pelo rust-analyzer que não estão no conjunto LSP padrão.
-- Confira com `:Inspect` / `:lua =vim.lsp.semantic_tokens.get_at_pos()`.
set(0, '@lsp.type.selfKeyword',      { fg = p.keyword, italic = true })  -- self
set(0, '@lsp.type.selfTypeKeyword',  { fg = p.type_ })                   -- Self
set(0, '@lsp.type.builtinType',      { fg = p.type_ })                   -- u32, i64, bool, str, f64
set(0, '@lsp.type.builtinAttribute', { fg = p.macro })                   -- nomes em #[derive], #[inline]...
set(0, '@lsp.type.lifetime',         { fg = p.typeParam })               -- 'a, 'static
set(0, '@lsp.type.generic',          { fg = p.typeParam })               -- parâmetros genéricos <T>
set(0, '@lsp.type.typeAlias',        { fg = p.type_ })                   -- type Foo = ...
set(0, '@lsp.type.const',            { fg = p.constant })                -- const X: ...
set(0, '@lsp.type.static',           { fg = p.constant })                -- static X: ...
set(0, '@lsp.type.formatSpecifier',  { fg = p.regex })                   -- {}, {:?} em println!
set(0, '@lsp.type.boolean',          { fg = p.constantAlt })             -- true/false como token
set(0, '@lsp.type.unresolvedReference', { undercurl = true, sp = p.error_ })

-- rust-analyzer typemods (confirmados via :Inspect)
-- const X   -> @lsp.type.const + @lsp.typemod.const.constant + @lsp.typemod.const.declaration
-- static X  -> @lsp.type.static + mods
-- mut x     -> @lsp.typemod.variable.mutable
set(0, '@lsp.typemod.const.constant',           { fg = p.constant })
set(0, '@lsp.typemod.const.declaration',        { fg = p.constant })
set(0, '@lsp.typemod.variable.static',          { fg = p.constant })
set(0, '@lsp.typemod.variable.readonly',        { fg = p.constant })
set(0, '@lsp.typemod.variable.mutable',         { fg = p.variable, underline = true })
set(0, '@lsp.typemod.parameter.mutable',        { fg = p.param,    underline = true })
set(0, '@lsp.typemod.variable.callable',        { fg = p.func })
set(0, '@lsp.typemod.variable.constant',        { fg = p.constant })
set(0, '@lsp.typemod.selfKeyword.defaultLibrary', { fg = p.keyword, italic = true })
-- defaultLibrary = vindo da stdlib (Vec, Option, Some, None, Result, println!, etc.)
set(0, '@lsp.typemod.function.defaultLibrary',  { fg = p.funcBuiltin })
set(0, '@lsp.typemod.method.defaultLibrary',    { fg = p.funcBuiltin })
set(0, '@lsp.typemod.macro.defaultLibrary',     { fg = p.macro,  bold = true })
set(0, '@lsp.typemod.type.defaultLibrary',      { fg = p.funcBuiltin })
set(0, '@lsp.typemod.struct.defaultLibrary',    { fg = p.funcBuiltin })
set(0, '@lsp.typemod.enum.defaultLibrary',      { fg = p.funcBuiltin })
set(0, '@lsp.typemod.enumMember.defaultLibrary',{ fg = p.constantAlt, bold = true })  -- None, Some, Ok, Err
set(0, '@lsp.typemod.interface.defaultLibrary', { fg = p.funcBuiltin })
set(0, '@lsp.typemod.property.defaultLibrary',  { fg = p.property })
-- atributos com modifiers (ex.: #[tokio::main] é um attribute)
set(0, '@lsp.typemod.attributeBracket.attribute', { fg = p.constant })
set(0, '@lsp.typemod.decorator.attribute',        { fg = p.macro })

-- ============================================================================
-- Plugins
-- ============================================================================

-- Neogit
set(0, 'NeogitBranch',               { fg = p.purple })
set(0, 'NeogitRemote',               { fg = p.teal })
set(0, 'NeogitHunkHeader',           { fg = p.property, bg = p.bg5 })
set(0, 'NeogitHunkHeaderHighlight',  { fg = p.property, bg = p.bg4 })
set(0, 'NeogitDiffAdd',              { fg = p.added })
set(0, 'NeogitDiffAddHighlight',     { bg = p.bgGreen })
set(0, 'NeogitDiffDelete',           { fg = p.deleted })
set(0, 'NeogitDiffDeleteHighlight',  { bg = p.bgRed })
set(0, 'NeogitDiffContextHighlight', { bg = p.bg4 })
set(0, 'NeogitNotificationError',    { fg = p.error_ })
set(0, 'NeogitNotificationWarning',  { fg = p.warning })
set(0, 'NeogitNotificationInfo',     { fg = p.info })

-- Neotest
set(0, 'NeotestPassed',      { fg = p.added })
set(0, 'NeotestFailed',      { fg = p.error_ })
set(0, 'NeotestSkipped',     { fg = p.purple })
set(0, 'NeotestRunning',     { fg = p.teal })
set(0, 'NeotestFocused',     { underline = true })
set(0, 'NeotestMarked',      { fg = p.fg,       bold = true })
set(0, 'NeotestNamespace',   { fg = p.namespace_ })
set(0, 'NeotestDir',         { fg = p.namespace_ })
set(0, 'NeotestFile',        { fg = p.namespace_ })
set(0, 'NeotestAdapterName', { fg = p.fgMuted,  bold = true })

-- Neo-tree
set(0, 'NeoTreeNormal',               { fg = p.fg,        bg = p.bg2 })
set(0, 'NeoTreeTitleBar',             { fg = p.bg2,       bg = p.fgMuted })
set(0, 'NeoTreeFloatTitle',           { fg = p.fg })
set(0, 'NeoTreeFileName',             { fg = p.fg })
set(0, 'NeoTreeFileNameOpened',       { fg = p.fg })
set(0, 'NeoTreeDirectoryName',        { fg = p.namespace_ })
set(0, 'NeoTreeDirectoryIcon',        { fg = p.namespace_ })
set(0, 'NeoTreeIndentMarker',         { fg = p.bg5 })
set(0, 'NeoTreeRootName',             { fg = p.teal,      bold = true })
set(0, 'NeoTreeFileStats',            { fg = p.fgMuted })
set(0, 'NeoTreeFileStatsHeader',      { fg = p.teal,      bold = true })
set(0, 'NeoTreeDotfile',              { fg = p.macro })
set(0, 'NeoTreeSymbolicLinkTarget',   { fg = p.fgMuted })
set(0, 'NeoTreeMessage',              { fg = p.fgMuted,   italic = true })
set(0, 'NeoTreeFadeText1',            { fg = p.fgMuted })
set(0, 'NeoTreeFadeText2',            { fg = p.bg5 })
set(0, 'NeoTreeGitAdded',             { fg = p.added })
set(0, 'NeoTreeGitModified',          { fg = p.modified })
set(0, 'NeoTreeGitDeleted',           { fg = p.deleted })
set(0, 'NeoTreeGitUntracked',         { fg = p.purple })
set(0, 'NeoTreeGitIgnored',           { fg = p.fgMuted })
set(0, 'NeoTreeGitConflict',          { fg = p.warning,   italic = true })
set(0, 'NeoTreeTabActive',            { bold = true })
set(0, 'NeoTreeTabInactive',          { fg = p.fgMuted,   bg = p.bg3 })
set(0, 'NeoTreeTabSeparatorActive',   { fg = p.bg2 })
set(0, 'NeoTreeTabSeparatorInactive', { fg = p.bg2,       bg = p.bg3 })
set(0, 'NeoTreeModified',             { fg = p.modified })

-- NvimTree
set(0, 'NvimTreeNormal',           { fg = p.fg,        bg = p.bg2 })
set(0, 'NvimTreeFolderName',       { fg = p.namespace_ })
set(0, 'NvimTreeFolderIcon',       { fg = p.namespace_ })
set(0, 'NvimTreeOpenedFolderName', { fg = p.namespace_ })
set(0, 'NvimTreeOpenedFile',       { fg = p.fgMuted })
set(0, 'NvimTreeEmptyFolderName',  { fg = p.fgMuted })
set(0, 'NvimTreeIndentMarker',     { fg = p.bg5 })
set(0, 'NvimTreeRootFolder',       { fg = p.teal,      bold = true })
set(0, 'NvimTreeSymlink',          { fg = p.fgMuted })
set(0, 'NvimTreeSpecialFile',      { fg = p.macro })
set(0, 'NvimTreeImageFile',        { fg = p.fg })
set(0, 'NvimTreeGitNew',           { fg = p.added })
set(0, 'NvimTreeGitDirty',         { fg = p.modified })
set(0, 'NvimTreeGitDeleted',       { fg = p.deleted })
set(0, 'NvimTreeGitMerge',         { fg = p.modified })

-- Telescope
set(0, 'TelescopeBorder',         { fg = p.bg5 })
set(0, 'TelescopeSelectionCaret', { fg = p.teal })
set(0, 'TelescopeSelection',      { fg = p.fg,        bg = p.bg4 })

-- Dashboard / Alpha
set(0, 'AlphaHeader',      { fg = p.teal })
set(0, 'AlphaFooter',      { fg = p.namespace_ })
set(0, 'AlphaButtons',     { fg = p.namespace_ })
set(0, 'AlphaShortcut',    { fg = p.teal })
set(0, 'AlphaHeaderLabel', { fg = p.teal })
set(0, 'DashboardFooter',  { fg = p.teal,      italic = true })

-- Mini
set(0, 'MiniStarterQuery',           { fg = p.fg })
set(0, 'MiniStarterItemPrefix',      { fg = p.fgMuted })
set(0, 'MiniStarterItemBullet',      { fg = p.fgMuted })
set(0, 'MiniStarterSection',         { fg = p.keyword })
set(0, 'MiniStarterFooter',          { fg = p.teal,      italic = true })
set(0, 'MiniStarterCurrent',         { nocombine = true })
set(0, 'MiniStatuslineModeNormal',   { fg = p.bg1,       bg = p.teal,        bold = true })
set(0, 'MiniStatuslineModeInsert',   { fg = p.bg1,       bg = p.typeParam,   bold = true })
set(0, 'MiniStatuslineModeVisual',   { fg = p.bg1,       bg = p.purple,      bold = true })
set(0, 'MiniStatuslineModeReplace',  { fg = p.bg1,       bg = p.keyword,     bold = true })
set(0, 'MiniStatuslineModeCommand',  { fg = p.bg1,       bg = p.namespace_,  bold = true })
set(0, 'MiniStatuslineModeOther',    { fg = p.bg1,       bg = p.namespace_,  bold = true })
set(0, 'MiniStatuslineDevinfo',      { fg = p.fg,        bg = p.bg4 })
set(0, 'MiniStatuslineFileinfo',     { fg = p.fg,        bg = p.bg4 })
set(0, 'MiniTablineCurrent',             { fg = p.fg,    bg = p.fgMuted,   bold = true })
set(0, 'MiniTablineVisible',             { fg = p.fg,    bg = p.bg4 })
set(0, 'MiniTablineHidden',              { fg = p.fgMuted, bg = p.bg4 })
set(0, 'MiniTablineModifiedCurrent',     { fg = p.fgMuted, bg = p.fg,      bold = true })
set(0, 'MiniTablineModifiedVisible',     { fg = p.bg4,   bg = p.fg })
set(0, 'MiniTablineModifiedHidden',      { fg = p.bg4,   bg = p.fgMuted })
set(0, 'MiniTablineTabpagesection',      { fg = p.fg,    bg = p.bg3,       bold = true })
set(0, 'MiniHipatternsNote',             { fg = p.bg1,   bg = p.info,      bold = true })
set(0, 'MiniHipatternsTodo',             { fg = p.bg1,   bg = p.teal,      bold = true })
set(0, 'MiniHipatternsFixme',            { fg = p.bg1,   bg = p.error_,    bold = true })
set(0, 'MiniHipatternsHack',             { fg = p.bg1,   bg = p.purple,    bold = true })
set(0, 'MiniIndentscopePrefix',          { nocombine = true })
set(0, 'MiniTrailspace',                 { bg = p.error_ })
set(0, 'MiniJump',                       { fg = p.bg1,   bg = p.purple })
set(0, 'MiniJump2dSpot',                 { fg = p.typeParam,  bold = true })
set(0, 'MiniJump2dSpotUnique',           { fg = p.teal,       bold = true })
set(0, 'MiniJump2dSpotAhead',            { fg = p.typeParam,  bg = p.bg2,   nocombine = true })
set(0, 'MiniDiffSignAdd',                { fg = p.added })
set(0, 'MiniDiffSignChange',             { fg = p.modified })
set(0, 'MiniDiffSignDelete',             { fg = p.deleted })
set(0, 'MiniCompletionActiveParameter',  { underline = true })
set(0, 'MiniTestFail',                   { fg = p.error_,     bold = true })
set(0, 'MiniTestPass',                   { fg = p.teal,       bold = true })
set(0, 'MiniTestEmphasis',               { bold = true })
set(0, 'MiniDepsTitleError',             { fg = p.bg1,        bg = p.error_ })
set(0, 'MiniDepsTitleUpdate',            { fg = p.bg1,        bg = p.teal })
set(0, 'MiniFilesFile',                  { fg = p.fg })
set(0, 'MiniFilesTitleFocused',          { fg = p.fg,         bold = true })
set(0, 'MiniAnimateCursor',              { reverse = true,    nocombine = true })
set(0, 'MiniIconsGreen',    { fg = p.added })
set(0, 'MiniIconsRed',      { fg = p.error_ })
set(0, 'MiniIconsYellow',   { fg = p.warning })
set(0, 'MiniIconsBlue',     { fg = p.func })
set(0, 'MiniIconsPurple',   { fg = p.purple })
set(0, 'MiniIconsAzure',    { fg = p.teal })
set(0, 'MiniIconsCyan',     { fg = p.cyan })
set(0, 'MiniIconsOrange',   { fg = p.warning })
set(0, 'MiniIconsGrey',     { fg = p.fgBright })

-- DAP UI
set(0, 'DapUINormalNC',               { bg = p.bg3 })
set(0, 'DapUIStepBackNC',             { bg = p.bg3 })
set(0, 'DapUIStepIntoNC',             { bg = p.bg3 })
set(0, 'DapUIStepOverNC',             { bg = p.bg3 })
set(0, 'DapUIStepOutNC',              { bg = p.bg3 })
set(0, 'DapUIRestartNC',              { bg = p.bg3 })
set(0, 'DapUIPlayPauseNC',            { bg = p.bg3 })
set(0, 'DapUIStopNC',                 { bg = p.bg3 })
set(0, 'DapUIUnavailableNC',          { bg = p.bg3 })
set(0, 'DapUIVariable',               { fg = p.fg })
set(0, 'DapUIValue',                  { fg = p.fg })
set(0, 'DapUIModifiedValue',          { fg = p.teal,      bold = true })
set(0, 'DapUIScope',                  { fg = p.namespace_ })
set(0, 'DapUIBreakpointsPath',        { fg = p.namespace_ })
set(0, 'DapUIBreakpointsInfo',        { fg = p.namespace_ })
set(0, 'DapUIBreakpointsCurrentLine', { fg = p.teal,      bold = true })
set(0, 'DapUIBreakpointsDisabledLine',{ fg = p.fgMuted })
set(0, 'DapUIWatchesEmpty',           { fg = p.error_ })
set(0, 'DapUIWatchesError',           { fg = p.error_ })
set(0, 'DapUIWatchesValue',           { fg = p.purple })
set(0, 'DapUIStoppedThread',          { fg = p.namespace_ })
set(0, 'DapUIDecoration',             { fg = p.fgMuted })
set(0, 'DapBreak',                    { fg = p.error_ })
set(0, 'DapStop',                     { fg = p.fgMuted })

-- Aerial
set(0, 'AerialGuide', { fg = p.bg5 })

-- Hop / Leap / Lightspeed
set(0, 'HopNextKey',         { fg = p.teal,      bold = true })
set(0, 'HopNextKey1',        { fg = p.namespace_, bold = true })
set(0, 'HopNextKey2',        { fg = p.typeParam })
set(0, 'HopUnmatched',       { fg = p.fgMuted })
set(0, 'LeapBackdrop',       { fg = p.fgMuted })
set(0, 'LeapLabelPrimary',   { fg = p.bg2,       bg = p.teal })
set(0, 'LeapLabelSecondary', { fg = p.bg2,       bg = p.typeParam })
set(0, 'LeapMatch',          { fg = p.bg2,       bg = p.teal })
set(0, 'LightspeedGreyWash', { fg = p.fgMuted })
set(0, 'PounceMatch',        { fg = p.fg,        bg = p.fgMuted })
set(0, 'PounceGap',          { fg = p.fg,        bg = p.bg4 })
set(0, 'PounceAccept',       { fg = p.bg2,       bg = p.teal })
set(0, 'PounceAcceptBest',   { fg = p.bg2,       bg = p.typeParam })

-- Sneak
set(0, 'Sneak',      { fg = p.bg1,  bg = p.purple })
set(0, 'SneakScope', { bg = p.bg4 })

-- Blink / Cmp
set(0, 'BlinkCmpKindDefault',     { fg = p.fg })
set(0, 'BlinkCmpKindSnippet',     { fg = p.fg })
set(0, 'BlinkCmpLabel',           { fg = p.fg })
set(0, 'BlinkCmpLabelMatch',      { fg = p.teal })
set(0, 'BlinkCmpLabelDeprecated', { fg = p.fgMuted,  strikethrough = true })
set(0, 'BlinkCmpDoc',             { fg = p.fg,        bg = p.bg2 })
set(0, 'BlinkCmpDocBorder',       { fg = p.bg5,       bg = p.bg2 })
set(0, 'CmpItemKindDefault',      { fg = p.fg })
set(0, 'CmpItemKindSnippet',      { fg = p.fg })
set(0, 'CmpItemAbbr',             { fg = p.fg })
set(0, 'CmpItemAbbrMatch',        { fg = p.teal })
set(0, 'CmpItemAbbrMatchFuzzy',   { fg = p.teal })
set(0, 'CmpItemAbbrDeprecated',   { fg = p.fgMuted,   strikethrough = true })
set(0, 'CmpDocumentation',        { fg = p.fg,        bg = p.bg2 })
set(0, 'CmpDocumentationBorder',  { fg = p.bg5,       bg = p.bg2 })

-- Slimline
set(0, 'Slimline',         { fg = p.fg,    bg = p.bg3 })
set(0, 'SlimlineInactive', { fg = p.fg,    bg = p.bg3 })
set(0, 'SlimlineModeNormal',  { fg = p.bg1, bg = p.teal })
set(0, 'SlimlineModeInsert',  { fg = p.bg1, bg = p.typeParam })
set(0, 'SlimlineModeVisual',  { fg = p.bg1, bg = p.purple })
set(0, 'SlimlineModeReplace', { fg = p.bg1, bg = p.keyword })
set(0, 'SlimlineModeCommand', { fg = p.bg1, bg = p.namespace_ })
set(0, 'SlimlineModeOther',   { fg = p.bg1, bg = p.namespace_ })
set(0, 'SlimlineModeSecondary', { fg = p.bg1, bg = p.fgMuted })
set(0, 'SlimlineModeNormalSep',    { fg = p.teal,       bg = p.bg3 })
set(0, 'SlimlineModeInsertSep',    { fg = p.typeParam,  bg = p.bg3 })
set(0, 'SlimlineModeVisualSep',    { fg = p.purple,     bg = p.bg3 })
set(0, 'SlimlineModeReplaceSep',   { fg = p.keyword,    bg = p.bg3 })
set(0, 'SlimlineModeCommandSep',   { fg = p.namespace_, bg = p.bg3 })
set(0, 'SlimlineModeOtherSep',     { fg = p.namespace_, bg = p.bg3 })
set(0, 'SlimlineModeSecondarySep', { fg = p.fgMuted,    bg = p.bg3 })
set(0, 'SlimlineModeNormalSep2Sec',    { fg = p.teal,       bg = p.fgMuted })
set(0, 'SlimlineModeInsertSep2Sec',    { fg = p.typeParam,  bg = p.fgMuted })
set(0, 'SlimlineModeVisualSep2Sec',    { fg = p.purple,     bg = p.fgMuted })
set(0, 'SlimlineModeReplaceSep2Sec',   { fg = p.keyword,    bg = p.fgMuted })
set(0, 'SlimlineModeCommandSep2Sec',   { fg = p.namespace_, bg = p.fgMuted })
set(0, 'SlimlineModeOtherSep2Sec',     { fg = p.namespace_, bg = p.fgMuted })
set(0, 'SlimlineGitPrimary',        { fg = p.bg2,       bg = p.fg })
set(0, 'SlimlineGitPrimarySep',     { fg = p.fg,        bg = p.bg3 })
set(0, 'SlimlineGitPrimarySep2Sec', { fg = p.fg,        bg = p.fgMuted })
set(0, 'SlimlineGitSecondary',      { fg = p.bg2,       bg = p.fgMuted })
set(0, 'SlimlineGitSecondarySep',   { fg = p.fgMuted,   bg = p.bg3 })
set(0, 'SlimlinePathPrimary',        { fg = p.bg2,       bg = p.fg })
set(0, 'SlimlinePathPrimarySep',     { fg = p.fg,        bg = p.bg3 })
set(0, 'SlimlinePathPrimarySep2Sec', { fg = p.fg,        bg = p.fgMuted })
set(0, 'SlimlinePathSecondary',      { fg = p.bg2,       bg = p.fgMuted })
set(0, 'SlimlinePathSecondarySep',   { fg = p.fgMuted,   bg = p.bg3 })
set(0, 'SlimlineFiletype_lspPrimary',        { fg = p.bg2,     bg = p.fg })
set(0, 'SlimlineFiletype_lspPrimarySep',     { fg = p.fg,      bg = p.bg3 })
set(0, 'SlimlineFiletype_lspPrimarySep2Sec', { fg = p.fg,      bg = p.fgMuted })
set(0, 'SlimlineFiletype_lspSecondary',      { fg = p.bg2,     bg = p.fgMuted })
set(0, 'SlimlineFiletype_lspSecondarySep',   { fg = p.fgMuted, bg = p.bg3 })
set(0, 'SlimlineDiagnosticsError',     { fg = p.bg2,    bg = p.error_ })
set(0, 'SlimlineDiagnosticsWarn',      { fg = p.bg2,    bg = p.purple })
set(0, 'SlimlineDiagnosticsInfo',      { fg = p.bg2,    bg = p.info })
set(0, 'SlimlineDiagnosticsHint',      { fg = p.bg2,    bg = p.hint })
set(0, 'SlimlineDiagnosticsSecondary', { fg = p.bg2,    bg = p.fgMuted })
set(0, 'SlimlineDiagnosticsErrorSep',  { fg = p.error_, bg = p.bg3 })
set(0, 'SlimlineDiagnosticsWarnSep',   { fg = p.purple, bg = p.bg3 })
set(0, 'SlimlineDiagnosticsInfoSep',   { fg = p.info,   bg = p.bg3 })
set(0, 'SlimlineDiagnosticsHintSep',   { fg = p.hint,   bg = p.bg3 })
set(0, 'SlimlineDiagnosticsSecondarySep', { fg = p.fgMuted, bg = p.bg3 })

-- Bufferline / Barbar
set(0, 'BufferCurrent',       { fg = p.fg,       bg = p.fgMuted })
set(0, 'BufferCurrentMod',    { fg = p.purple,   bg = p.fgMuted })
set(0, 'BufferCurrentSign',   { fg = p.teal,     bg = p.fgMuted })
set(0, 'BufferCurrentIndex',  { fg = p.teal,     bg = p.fgMuted })
set(0, 'BufferCurrentTarget', { fg = p.error_,   bg = p.fgMuted })
set(0, 'BufferVisible',       { fg = p.fg,       bg = p.bg2 })
set(0, 'BufferVisibleMod',    { fg = p.purple,   bg = p.bg2 })
set(0, 'BufferVisibleSign',   { fg = p.namespace_, bg = p.bg2 })
set(0, 'BufferVisibleIndex',  { fg = p.namespace_, bg = p.bg2 })
set(0, 'BufferVisibleTarget', { fg = p.error_,   bg = p.bg2 })
set(0, 'BufferInactive',      { fg = p.fgMuted,  bg = p.bg2 })
set(0, 'BufferInactiveMod',   { fg = p.bg4,      bg = p.bg2 })
set(0, 'BufferInactiveSign',  { fg = p.bg5,      bg = p.bg2 })
set(0, 'BufferInactiveIndex', { fg = p.fgMuted,  bg = p.bg2 })
set(0, 'BufferInactiveTarget',{ fg = p.error_,   bg = p.bg2 })
set(0, 'BufferTabpage',       { fg = p.bg5,      bg = p.bg2 })
set(0, 'BufferTabpages',      { bg = p.bg2 })

-- Notify
set(0, 'NotifyERRORTitle',   { fg = p.error_ })
set(0, 'NotifyERRORBorder',  { fg = p.bgRed })
set(0, 'NotifyWARNTitle',    { fg = p.warning })
set(0, 'NotifyWARNBorder',   { fg = p.warning })
set(0, 'NotifyINFOTitle',    { fg = p.info })
set(0, 'NotifyINFOBorder',   { fg = p.bgBlue })
set(0, 'NotifyINFOTitle40',  { fg = p.bg2 })
set(0, 'NotifyINFOBody40',   { fg = p.bg2,    bg = p.bg2 })
set(0, 'NotifyINFOIcon40',   { fg = p.bg2 })
set(0, 'NotifyINFOBorder40', { fg = p.bg1 })
set(0, 'NotifyDEBUGTitle',   { fg = p.teal })
set(0, 'NotifyDEBUGBorder',  { fg = p.bgGreen })
set(0, 'NotifyTRACETitle',   { fg = p.fgMuted })
set(0, 'NotifyTRACEBorder',  { fg = p.bg5 })

-- Neominimap
set(0, 'NeominimapErrorLine', { bg = p.error_ })
set(0, 'NeominimapWarnLine',  { bg = p.purple })
set(0, 'NeominimapInfoLine',  { bg = p.info })
set(0, 'NeominimapHintLine',  { bg = p.hint })
set(0, 'NeominimapErrorSign', { fg = p.error_ })
set(0, 'NeominimapWarnSign',  { fg = p.purple })
set(0, 'NeominimapInfoSign',  { fg = p.info })
set(0, 'NeominimapHintSign',  { fg = p.hint })
set(0, 'NeominimapErrorIcon', { fg = p.error_ })
set(0, 'NeominimapWarnIcon',  { fg = p.purple })
set(0, 'NeominimapInfoIcon',  { fg = p.info })
set(0, 'NeominimapHintIcon',  { fg = p.hint })
set(0, 'NeominimapGitChangeLine', { bg = p.modified })
set(0, 'NeominimapGitChangeIcon', { fg = p.modified })
set(0, 'NeominimapGitChangeSign', { fg = p.modified })
set(0, 'NeominimapGitAddLine',    { bg = p.teal })
set(0, 'NeominimapGitAddIcon',    { fg = p.added })
set(0, 'NeominimapGitAddSign',    { fg = p.added })
set(0, 'NeominimapGitDeleteLine', { bg = p.error_ })
set(0, 'NeominimapGitDeleteIcon', { fg = p.error_ })
set(0, 'NeominimapGitDeleteSign', { fg = p.error_ })
set(0, '_Neominimap.@constructor',           { fg = p.namespace_ })
set(0, '_Neominimap.@number',                { fg = p.number })
set(0, '_Neominimap.@operator',              { fg = p.operator })
set(0, '_Neominimap.@property',              { fg = p.property })
set(0, '_Neominimap.@string',                { fg = p.string_ })
set(0, '_Neominimap.@variable',              { fg = p.fg })
set(0, '_Neominimap.@variable.member',       { fg = p.property })
set(0, '_Neominimap.@punctuation.delimiter', { fg = p.fg })
set(0, '_Neominimap.@punctuation.bracket',   { fg = p.fg })
set(0, '_Neominimap.@comment',               { fg = p.comment })
set(0, '_Neominimap.@keyword',               { fg = p.keyword })
set(0, '_Neominimap.@boolean',               { fg = p.constantAlt })

-- TinyInlineDiagnostic
set(0, 'TinyInlineDiagnosticVirtualTextHint',  { fg = p.hint,    bg = p.bgGreen })
set(0, 'TinyInlineDiagnosticVirtualTextWarn',  { fg = p.warning, bg = p.bgYellow })
set(0, 'TinyInlineDiagnosticVirtualTextError', { fg = p.error_,  bg = p.bgRed })
set(0, 'TinyInlineDiagnosticVirtualTextInfo',  { fg = p.info,    bg = p.bgBlue })
set(0, 'TinyInlineDiagnosticVirtualTextBg',    { bg = p.bg5 })
set(0, 'TinyInlineDiagnosticVirtualTextArrow', { fg = p.bg5,     bg = p.bg5 })
set(0, 'TinyInlineDiagnosticVirtualTextArrowNoBg',  { fg = p.bg5 })
set(0, 'TinyInlineDiagnosticVirtualTextErrorNoBg',  { fg = p.error_ })
set(0, 'TinyInlineDiagnosticVirtualTextWarnNoBg',   { fg = p.warning })
set(0, 'TinyInlineDiagnosticVirtualTextInfoNoBg',   { fg = p.info })
set(0, 'TinyInlineDiagnosticVirtualTextHintNoBg',   { fg = p.hint })
set(0, 'TinyInlineDiagnosticVirtualTextErrorMixError', { fg = p.error_,  bg = p.bgRed })
set(0, 'TinyInlineDiagnosticVirtualTextErrorMixWarn',  { fg = p.error_,  bg = p.bgYellow })
set(0, 'TinyInlineDiagnosticVirtualTextErrorMixInfo',  { fg = p.error_,  bg = p.bgBlue })
set(0, 'TinyInlineDiagnosticVirtualTextErrorMixHint',  { fg = p.error_,  bg = p.bgGreen })
set(0, 'TinyInlineDiagnosticVirtualTextWarnMixWarn',   { fg = p.warning, bg = p.bgYellow })
set(0, 'TinyInlineDiagnosticVirtualTextWarnMixInfo',   { fg = p.warning, bg = p.bgBlue })
set(0, 'TinyInlineDiagnosticVirtualTextWarnMixHint',   { fg = p.warning, bg = p.bgGreen })
set(0, 'TinyInlineDiagnosticVirtualTextInfoMixWarn',   { fg = p.info,    bg = p.bgYellow })
set(0, 'TinyInlineDiagnosticVirtualTextInfoMixInfo',   { fg = p.info,    bg = p.bgBlue })
set(0, 'TinyInlineDiagnosticVirtualTextInfoMixHint',   { fg = p.info,    bg = p.bgGreen })
set(0, 'TinyInlineDiagnosticVirtualTextHintMixInfo',   { fg = p.hint,    bg = p.bgBlue })
set(0, 'TinyInlineDiagnosticVirtualTextHintMixWarn',   { fg = p.hint,    bg = p.bgYellow })
set(0, 'TinyInlineDiagnosticVirtualTextHintMixError',  { fg = p.hint,    bg = p.bgRed })
set(0, 'TinyInlineDiagnosticVirtualTextHintMixHint',   { fg = p.hint,    bg = p.bgGreen })
set(0, 'TinyInlineDiagnosticVirtualTextErrorCursorLine', { fg = p.error_ })
set(0, 'TinyInlineDiagnosticVirtualTextWarnCursorLine',  { fg = p.warning })
set(0, 'TinyInlineDiagnosticVirtualTextInfoCursorLine',  { fg = p.info })
set(0, 'TinyInlineDiagnosticVirtualTextHintCursorLine',  { fg = p.hint })
set(0, 'TinyInlineInvDiagnosticVirtualTextHint',  { fg = p.bgGreen,  bg = p.bg5 })
set(0, 'TinyInlineInvDiagnosticVirtualTextWarn',  { fg = p.bgYellow, bg = p.bg5 })
set(0, 'TinyInlineInvDiagnosticVirtualTextError', { fg = p.bgRed,    bg = p.bg5 })
set(0, 'TinyInlineInvDiagnosticVirtualTextInfo',  { fg = p.bgBlue,   bg = p.bg5 })
set(0, 'TinyInlineInvDiagnosticVirtualTextHintNoBg',  { fg = p.bgGreen })
set(0, 'TinyInlineInvDiagnosticVirtualTextWarnNoBg',  { fg = p.bgYellow })
set(0, 'TinyInlineInvDiagnosticVirtualTextErrorNoBg', { fg = p.bgRed })
set(0, 'TinyInlineInvDiagnosticVirtualTextInfoNoBg',  { fg = p.bgBlue })
set(0, 'TinyInlineInvDiagnosticVirtualTextHintCursorLine',  { fg = p.bgGreen })
set(0, 'TinyInlineInvDiagnosticVirtualTextWarnCursorLine',  { fg = p.bgYellow })
set(0, 'TinyInlineInvDiagnosticVirtualTextErrorCursorLine', { fg = p.bgRed })
set(0, 'TinyInlineInvDiagnosticVirtualTextInfoCursorLine',  { fg = p.bgBlue })

-- SmearCursor
set(0, 'SmearCursor1',  { fg = p.bg5,     blend = 0 })
set(0, 'SmearCursor2',  { fg = p.fgMuted, blend = 0 })
set(0, 'SmearCursor3',  { fg = p.fgMuted, blend = 0 })
set(0, 'SmearCursor4',  { fg = p.fgMuted, blend = 0 })
set(0, 'SmearCursor5',  { fg = p.fgMuted, blend = 0 })
set(0, 'SmearCursor6',  { fg = p.fgMuted, blend = 0 })
set(0, 'SmearCursor7',  { fg = p.fgMuted, blend = 0 })
set(0, 'SmearCursor8',  { fg = p.fgMuted, blend = 0 })
set(0, 'SmearCursor9',  { fg = p.teal,    blend = 0 })
set(0, 'SmearCursor10', { fg = p.teal,    blend = 0 })
set(0, 'SmearCursor11', { fg = p.teal,    blend = 0 })
set(0, 'SmearCursor12', { fg = p.teal,    blend = 0 })
set(0, 'SmearCursor13', { fg = p.teal,    blend = 0 })
set(0, 'SmearCursor14', { fg = p.teal,    blend = 0 })
set(0, 'SmearCursor15', { fg = p.teal,    blend = 0 })
set(0, 'SmearCursor16', { fg = p.teal,    blend = 0 })
set(0, 'SmearCursorHideable',   { fg = p.fgBright,  blend = 100 })
set(0, 'SmearCursorInverted1',  { fg = p.bg3, bg = p.fgMuted, blend = 0 })
set(0, 'SmearCursorInverted2',  { fg = p.bg3, bg = p.fgMuted, blend = 0 })
set(0, 'SmearCursorInverted3',  { fg = p.bg3, bg = p.fgMuted, blend = 0 })
set(0, 'SmearCursorInverted4',  { fg = p.bg3, bg = p.fgMuted, blend = 0 })
set(0, 'SmearCursorInverted5',  { fg = p.bg3, bg = p.fgMuted, blend = 0 })
set(0, 'SmearCursorInverted6',  { fg = p.bg3, bg = p.fgMuted, blend = 0 })
set(0, 'SmearCursorInverted7',  { fg = p.bg3, bg = p.fgMuted, blend = 0 })
set(0, 'SmearCursorInverted8',  { fg = p.bg3, bg = p.teal,    blend = 0 })
set(0, 'SmearCursorInverted9',  { fg = p.bg3, bg = p.teal,    blend = 0 })
set(0, 'SmearCursorInverted10', { fg = p.bg3, bg = p.teal,    blend = 0 })
set(0, 'SmearCursorInverted11', { fg = p.bg3, bg = p.teal,    blend = 0 })
set(0, 'SmearCursorInverted12', { fg = p.bg3, bg = p.teal,    blend = 0 })
set(0, 'SmearCursorInverted13', { fg = p.bg3, bg = p.teal,    blend = 0 })
set(0, 'SmearCursorInverted14', { fg = p.bg3, bg = p.teal,    blend = 0 })
set(0, 'SmearCursorInverted15', { fg = p.bg3, bg = p.teal,    blend = 0 })
set(0, 'SmearCursorInverted16', { fg = p.bg3, bg = p.teal,    blend = 0 })

-- SmoothCursor
set(0, 'SmoothCursor',        { fg = p.teal })
set(0, 'SmoothCursorRed',     { fg = p.error_ })
set(0, 'SmoothCursorRed1',    { fg = p.error_ })
set(0, 'SmoothCursorRed2',    { fg = p.error_ })
set(0, 'SmoothCursorBlue',    { fg = p.info })
set(0, 'SmoothCursorBlue1',   { fg = p.bgBlue })
set(0, 'SmoothCursorBlue2',   { fg = p.bgBlue })
set(0, 'SmoothCursorBlue3',   { fg = p.bgBlue })
set(0, 'SmoothCursorGreen',   { fg = p.added })
set(0, 'SmoothCursorYellow',  { fg = p.warning })
set(0, 'SmoothCursorYellow1', { fg = p.warning })
set(0, 'SmoothCursorYellow2', { fg = p.warning })
set(0, 'SmoothCursorOrange',  { fg = p.warning })
set(0, 'SmoothCursorPurple',  { fg = p.purple })
set(0, 'SmoothCursorAqua',    { fg = p.teal })
set(0, 'SmoothCursorScarlet1',{ fg = p.error_ })
set(0, 'SmoothCursorScarlet2',{ fg = p.keyword })

-- RainbowDelimiter
set(0, 'RainbowDelimiterRed',    { fg = p.keyword })
set(0, 'RainbowDelimiterOrange', { fg = p.warning })
set(0, 'RainbowDelimiterYellow', { fg = p.warning })
set(0, 'RainbowDelimiterGreen',  { fg = p.added })
set(0, 'RainbowDelimiterCyan',   { fg = p.teal })
set(0, 'RainbowDelimiterBlue',   { fg = p.func })
set(0, 'RainbowDelimiterPurple', { fg = p.purple })
set(0, 'TSRainbowRed',     { fg = p.keyword })
set(0, 'TSRainbowOrange',  { fg = p.warning })
set(0, 'TSRainbowYellow',  { fg = p.warning })
set(0, 'TSRainbowGreen',   { fg = p.added })
set(0, 'TSRainbowCyan',    { fg = p.teal })
set(0, 'TSRainbowBlue',    { fg = p.func })
set(0, 'TSRainbowViolet',  { fg = p.purple })
set(0, 'rainbowcol1', { fg = p.keyword })
set(0, 'rainbowcol2', { fg = p.warning })
set(0, 'rainbowcol3', { fg = p.warning })
set(0, 'rainbowcol4', { fg = p.added })
set(0, 'rainbowcol5', { fg = p.teal })
set(0, 'rainbowcol6', { fg = p.func })
set(0, 'rainbowcol7', { fg = p.purple })

-- IndentBlankline
set(0, 'IndentBlanklineChar',         { fg = p.bg5 })
set(0, 'IndentBlanklineContextChar',  { fg = p.teal })
set(0, 'IndentBlanklineContextStart', { underline = true, sp = p.teal })
set(0, 'IndentBlanklineIndent1',      { fg = p.keyword })
set(0, 'IndentBlanklineIndent2',      { fg = p.warning })
set(0, 'IndentBlanklineIndent3',      { fg = p.teal })
set(0, 'IndentBlanklineIndent4',      { fg = p.func })
set(0, 'IndentBlanklineIndent5',      { fg = p.info })
set(0, 'IndentBlanklineIndent6',      { fg = p.purple })

-- DevIcon
set(0, 'DevIconSvg',         { fg = p.warning })
set(0, 'DevIconDb',          { fg = p.fgMuted })
set(0, 'DevIconGitModules',  { fg = p.keyword })
set(0, 'DevIconPNPMFile',    { fg = p.warning })
set(0, 'DevIconTerminal',    { fg = p.teal })
set(0, 'DevIconHyprlock',    { fg = p.namespace_ })
set(0, 'DevIconSh',          { fg = p.fgMuted })
set(0, 'DevIconCp',          { fg = p.namespace_ })
set(0, 'DevIconSway',        { fg = p.fgMuted })
set(0, 'DevIconPng',         { fg = p.keyword })
set(0, 'DevIconKotlin',      { fg = p.purple })
set(0, 'DevIconErl',         { fg = p.keyword })
set(0, 'DevIconVue',         { fg = p.teal })
set(0, 'DevIconYaml',        { fg = p.keyword })
set(0, 'DevIconHtml',        { fg = p.keyword })
set(0, 'DevIconCss',         { fg = p.purple })
set(0, 'DevIconDockerfile',  { fg = p.namespace_ })
set(0, 'DevIconGo',          { fg = p.namespace_ })
set(0, 'DevIconRs',          { fg = p.warning })
set(0, 'DevIconPy',          { fg = p.namespace_ })
set(0, 'DevIconJs',          { fg = p.warning })
set(0, 'DevIconTs',          { fg = p.namespace_ })
set(0, 'DevIconTsx',         { fg = p.namespace_ })
set(0, 'DevIconJsx',         { fg = p.namespace_ })
set(0, 'DevIconLua',         { fg = p.namespace_ })
set(0, 'DevIconJson',        { fg = p.warning })
set(0, 'DevIconMd',          { fg = p.fg })
set(0, 'DevIconToml',        { fg = p.keyword })
set(0, 'DevIconYml',         { fg = p.keyword })
set(0, 'DevIconZsh',         { fg = p.teal })
set(0, 'DevIconBash',        { fg = p.teal })
set(0, 'DevIconBashrc',      { fg = p.teal })
set(0, 'DevIconVim',         { fg = p.fg })
set(0, 'DevIconGitIgnore',   { fg = p.keyword })
set(0, 'DevIconGitLogo',     { fg = p.keyword })
set(0, 'DevIconPackageJson', { fg = p.keyword })
set(0, 'DevIconTxt',         { fg = p.fg })
set(0, 'DevIconCsv',         { fg = p.fg })
set(0, 'DevIconDefault',     { fg = p.fgMuted })
set(0, 'DevIconMarkdown',    { fg = p.fg })
set(0, 'DevIconReadme',      { fg = p.fgBright })
set(0, 'DevIconLock',        { fg = p.fgMuted })
set(0, 'DevIconSql',         { fg = p.namespace_ })
set(0, 'DevIconNix',         { fg = p.namespace_ })
set(0, 'DevIconSwift',       { fg = p.keyword })
set(0, 'DevIconDart',        { fg = p.namespace_ })
set(0, 'DevIconZig',         { fg = p.warning })
set(0, 'DevIconScss',        { fg = p.keyword })
set(0, 'DevIconSass',        { fg = p.keyword })
set(0, 'DevIconPhp',         { fg = p.purple })
set(0, 'DevIconRb',          { fg = p.keyword })
set(0, 'DevIconJava',        { fg = p.keyword })
set(0, 'DevIconScala',       { fg = p.keyword })
set(0, 'DevIconCs',          { fg = p.fg })
set(0, 'DevIconCpp',         { fg = p.namespace_ })
set(0, 'DevIconC',           { fg = p.namespace_ })
set(0, 'DevIconH',           { fg = p.fgMuted })
set(0, 'DevIconPdf',         { fg = p.keyword })
set(0, 'DevIconXlsx',        { fg = p.fg })
set(0, 'DevIconDocx',        { fg = p.namespace_ })
set(0, 'DevIconPptx',        { fg = p.keyword })
set(0, 'DevIconArch',        { fg = p.namespace_ })
set(0, 'DevIconDebian',      { fg = p.keyword })
set(0, 'DevIconUbuntu',      { fg = p.keyword })
set(0, 'DevIconFedora',      { fg = p.namespace_ })
set(0, 'DevIconApple',       { fg = p.fgMuted })
set(0, 'DevIconWindows',     { fg = p.namespace_ })
set(0, 'DevIconLinux',       { fg = p.fgBright })
set(0, 'DevIconTypeScript',  { fg = p.namespace_ })
set(0, 'DevIconElm',         { fg = p.namespace_ })
set(0, 'DevIconSvelte',      { fg = p.keyword })
set(0, 'DevIconVitestConfig',{ fg = p.fg })
set(0, 'DevIconAstro',       { fg = p.keyword })
set(0, 'DevIconTerraform',   { fg = p.purple })
set(0, 'DevIconPrisma',      { fg = p.namespace_ })
set(0, 'DevIconGradle',      { fg = p.namespace_ })

-- ============================================================================
-- Additional
-- ============================================================================
set(0, 'Todo',         { fg = p.bg2,  bg = p.info })
set(0, 'TodoFgTODO',   { fg = p.info })
set(0, 'TodoFgFIX',    { fg = p.error_ })
set(0, 'TodoFgWARN',   { fg = p.warning })
set(0, 'TodoFgNOTE',   { fg = p.teal })
set(0, 'TodoFgTEST',   { fg = p.namespace_ })
set(0, 'TodoFgPERF',   { fg = p.func })
set(0, 'TodoFgHACK',   { fg = p.purple })
set(0, 'TodoBgTODO',   { fg = p.bg2, bg = p.info,      bold = true })
set(0, 'TodoBgFIX',    { fg = p.bg2, bg = p.error_,    bold = true })
set(0, 'TodoBgWARN',   { fg = p.bg2, bg = p.warning,   bold = true })
set(0, 'TodoBgNOTE',   { fg = p.bg2, bg = p.teal,      bold = true })
set(0, 'TodoBgTEST',   { fg = p.bg2, bg = p.namespace_, bold = true })
set(0, 'TodoBgPERF',   { fg = p.bg2, bg = p.func,      bold = true })
set(0, 'TodoBgHACK',   { fg = p.bg2, bg = p.purple,    bold = true })
set(0, 'TodoSignTODO', { fg = p.info })
set(0, 'TodoSignFIX',  { fg = p.error_ })
set(0, 'TodoSignWARN', { fg = p.warning })
set(0, 'TodoSignNOTE', { fg = p.teal })
set(0, 'TodoSignTEST', { fg = p.namespace_ })
set(0, 'TodoSignPERF', { fg = p.func })
set(0, 'TodoSignHACK', { fg = p.purple })

set(0, 'ModesInsert',  { bg = p.typeParam })
set(0, 'ModesVisual',  { bg = p.purple })
set(0, 'ModesCopy',    { bg = p.teal })
set(0, 'ModesDelete',  { bg = p.error_ })

set(0, 'SnacksImageMath',          { fg = p.namespace_ })
set(0, 'NavicText',                { fg = p.fg })
set(0, 'NavicSeparator',           { fg = p.bg5 })
set(0, 'FernBranchText',           { fg = p.namespace_ })
set(0, 'NoiceHiddenCursor',        { nocombine = true, blend = 100 })
set(0, 'NoiceFormatProgressDone',  { fg = p.fg,        bg = p.fgMuted })
set(0, 'RedrawDebugNormal',        { reverse = true })
set(0, 'RedrawDebugClear',         { bg = p.fgMuted })
set(0, 'RedrawDebugComposed',      { bg = p.teal })
set(0, 'RedrawDebugRecompose',     { bg = p.error_ })
set(0, 'CocInlayHint',             { fg = p.fgMuted,   bg = p.bg4 })

set(0, 'GlyphPalette0',  { fg = p.bg4 })
set(0, 'GlyphPalette1',  { fg = p.error_ })
set(0, 'GlyphPalette2',  { fg = p.added })
set(0, 'GlyphPalette3',  { fg = p.warning })
set(0, 'GlyphPalette4',  { fg = p.func })
set(0, 'GlyphPalette5',  { fg = p.purple })
set(0, 'GlyphPalette6',  { fg = p.teal })
set(0, 'GlyphPalette7',  { fg = p.fg })
set(0, 'GlyphPalette8',  { fg = p.bg5 })
set(0, 'GlyphPalette9',  { fg = p.warning })
set(0, 'GlyphPalette10', { fg = p.added })
set(0, 'GlyphPalette11', { fg = p.warning })
set(0, 'GlyphPalette12', { fg = p.namespace_ })
set(0, 'GlyphPalette13', { fg = p.purple })
set(0, 'GlyphPalette14', { fg = p.teal })
set(0, 'GlyphPalette15', { fg = p.fg })

set(0, 'typescriptParens', { fg = p.fg })
