return {
  'maskudo/devdocs.nvim',
  lazy = false,
  cmd = { 'DevDocs' },
  keys = {
    {
      '<leader>ds',
      mode = 'n',
      '<cmd>DevDocs get<cr>',
      desc = '[D]evdocs [S]earch',
    },
    {
      '<leader>di',
      mode = 'n',
      '<cmd>DevDocs install<cr>',
      desc = '[D]evdocs [I]nstall',
    },
    {
      '<leader>dd',
      mode = 'n',
      '<cmd>DevDocs delete<cr>',
      desc = '[D]evdoc [D]elete',
    },
  },
  opts = {
    ensure_installed = {
      'html',
      'css',
      'dom',
      'http',
      'tailwindcss',
      'angular',
      'react',
      'typescript',
      'c',
      'rust',
      'openjdk~25',
      'postgresql~18',
      'git',
      'nextjs',
      'node',
      'bash',
      'bun',
      'dart~2',
      'docker',
      'eslint',
      'express',
      'fastapi',
      'lua~5.1',
    },
  },
}
